In [1]:
from sklearn import datasets,metrics

In [2]:
# 观察数据结构
diabetes = datasets.load_diabetes()
print(diabetes.keys())
print(diabetes.data.shape,diabetes.target.shape)
print(diabetes.feature_names)
print(diabetes.data[0])
print(diabetes.target[:10])

dict_keys(['data', 'target', 'DESCR', 'feature_names'])
(442, 10) (442,)
['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']
[ 0.03807591  0.05068012  0.06169621  0.02187235 -0.0442235  -0.03482076
 -0.04340085 -0.00259226  0.01990842 -0.01764613]
[ 151.   75.  141.  206.  135.   97.  138.   63.  110.  310.]


In [7]:
# 划分数据集--未进行标准化
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test = train_test_split(diabetes.data,diabetes.target,random_state=0,test_size=0.25)
x_train=diabetes.data[:-20]  
y_train=diabetes.target[:-20]  
x_test=diabetes.data[-20:]  
y_test=diabetes.target[-20:] 
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(422, 10) (422,)
(20, 10) (20,)


### knn 算法做回归项目

In [8]:
# 导入库
from sklearn.neighbors import KNeighborsRegressor
# 实例化模型
knn = KNeighborsRegressor()
knn.fit(x_train,y_train)
print("训练集精度：",knn.score(x_train,y_train))
print("测试集精度：",knn.score(x_test,y_test))

训练集精度： 0.60298851084
测试集精度： 0.372150787803


In [9]:
# 标准化
from sklearn.preprocessing import StandardScaler
std_x = StandardScaler()
std_x_train = std_x.fit_transform(x_train)
std_x_test = std_x.fit_transform(x_test)
std_y = StandardScaler()
std_y_train = std_y.fit_transform(y_train.reshape(-1,1)).reshape(1,-1)[0]
std_y_test = std_y.fit_transform(y_test.reshape(-1,1)).reshape(1,-1)[0]
knn = KNeighborsRegressor()
knn.fit(std_x_train,std_y_train)
print("训练集精度：",knn.score(std_x_train,std_y_train))
print("测试集精度：",knn.score(std_x_test,std_y_test))

训练集精度： 0.603002055051
测试集精度： 0.489064318122


### 线性回归模型

In [6]:
# 导入库
from sklearn.linear_model import LinearRegression
# 模型实例化------标准化之前
lr = LinearRegression()
lr.fit(x_train,y_train)
print("训练集精度：",lr.score(x_train,y_train))
print("测试集精度：",lr.score(x_test,y_test))

训练集精度： 0.512226214779
测试集精度： 0.585075302269


In [7]:
# 标准化之后
lr_1 = LinearRegression()
lr_1.fit(std_x_train,std_y_train)
print("训练集精度：",lr_1.score(std_x_train,std_y_train))
print("训练集精度：",lr_1.score(std_x_test,std_y_test))

训练集精度： 0.512226214779
训练集精度： 0.636028197417


### 决策树

In [9]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor(max_depth=4,min_samples_leaf=5)
dt.fit(std_x_train,std_y_train)
print("训练集精度：",dt.score(std_x_train,std_y_train))
print("训练集精度：",dt.score(std_x_test,std_y_test))
print(dt)

训练集精度： 0.566672953371
训练集精度： 0.616053279204
DecisionTreeRegressor(criterion='mse', max_depth=4, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=5,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')


In [12]:
# 绘制决策树
from sklearn.tree import export_graphviz
from sklearn.externals.six import StringIO
import pydotplus
from io import StringIO
dot_data = StringIO()
export_graphviz(dt, out_file=dot_data,  # 绘制决策树
    feature_names=diabetes.feature_names,
    class_names=diabetes.target,
    filled=True, rounded=True,
    special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("diabetes.pdf")

True

### 随机森林

In [86]:
from sklearn.ensemble import RandomForestRegressor
rand_forest = RandomForestRegressor(max_depth=5,min_samples_leaf=10,n_estimators=100)
rand_forest.fit(std_x_train,std_y_train)
print("训练集精度：",rand_forest.score(std_x_train,std_y_train))
print("训练集精度：",rand_forest.score(std_x_test,std_y_test))
print(rand_forest)

训练集精度： 0.625720392671
训练集精度： 0.540244373945
RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=5,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=10, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)


### SVM

In [32]:
from sklearn.svm import SVR
svm = SVR(C=10.0,gamma=0.01)
svm.fit(std_x_train,std_y_train)
print(svm)
print("训练集精度：",svm.score(std_x_train,std_y_train))
print("测试集精度：",svm.score(std_x_test,std_y_test))

SVR(C=10.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.01,
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)
训练集精度： 0.561061800021
测试集精度： 0.688152975006


### sklern中的神经网络模型

In [212]:
from sklearn.neural_network import MLPRegressor
net = MLPRegressor(hidden_layer_sizes=(100,30,100))
net.fit(x_train,y_train)
print(net.predict(x_train)[:10])
print(y_train[:10])
print("训练集精度：",net.score(x_train,y_train))
print("训练集精度：",net.score(x_test,y_test))
print(net)

[ 180.81880633   78.13340229  163.29426302  156.0191971   130.93227209
   85.46026252   92.86741182  147.45201738  156.73911394  176.83547056]
[ 151.   75.  141.  206.  135.   97.  138.   63.  110.  310.]
训练集精度： 0.463526188673
训练集精度： 0.46535591292
MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 30, 100), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)


### 网上历程

In [176]:
import numpy as np  
from sklearn import datasets  
diabetes=datasets.load_diabetes() 
x_train=diabetes.data[:-20]  
y_train=diabetes.target[:-20]  
x_test=diabetes.data[-20:]  
y_test=diabetes.target[-20:]  
from sklearn import linear_model  
linreg=linear_model.LinearRegression()   #创建线性回归  
linreg.fit( x_train,y_train)  
linreg.predict( x_test )  
print("训练集精度",linreg.score( x_train,y_train))  
print("测试集精度：",linreg.score( x_test,y_test))

训练集精度 0.512226214779
测试集精度： 0.585075302269


### pytorch神经网络

In [35]:
import torch
from torch import nn
from torch.autograd import Variable

In [90]:
# 使用 Sequential 定义 3 层神经网络
net = nn.Sequential(
    nn.Linear(10,100),
    nn.ReLU(),
    nn.Linear(100,60),
    nn.ReLU(),
    nn.Linear(60,1)
)
print(net)
criteriton = nn.MSELoss()
optimizer = torch.optim.SGD(net.parameters(),lr=0.001)
print(x_train[:10])
x_train=diabetes.data[:-20]  
y_train=diabetes.target[:-20]  
x_test=diabetes.data[-20:]  
y_test=diabetes.target[-20:] 

Sequential(
  (0): Linear(in_features=10, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=60, bias=True)
  (3): ReLU()
  (4): Linear(in_features=60, out_features=1, bias=True)
)
[[ 0.03807591  0.05068012  0.06169621  0.02187235 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990842 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632783 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06832974 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567061 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286377 -0.02593034]
 [-0.08906294 -0.04464164 -0.01159501 -0.03665645  0.01219057  0.02499059
  -0.03603757  0.03430886  0.02269202 -0.00936191]
 [ 0.00538306 -0.04464164 -0.03638469  0.02187235  0.00393485  0.01559614
   0.00814208 -0.00259226 -0.03199144 -0.04664087]
 [-0.09269548 -0.04464164 -0.04069594 -0.01944209 -0.06899065 -0.07928784
   0.04127682 -0.0763945  -0.04118039 -0.09634616]
 [-0.04547248  0.05068012 -0.0471

In [93]:
out = net(Variable(torch.from_numpy(x_train)).float())
loss = criterion(out, torch.from_numpy(y_train).float())
print(loss)
optimizer.zero_grad()
loss.backward()
optimizer.step()
# out = net(Variable(torch.from_numpy(x_train)).float())
# loss = criterion(out, torch.from_numpy(y_train).float())
for i in range(1000):
    out = net(Variable(torch.from_numpy(x_train)).float())
    loss = criterion(out, torch.from_numpy(y_train).float())
    if i %100 ==0:
        print(loss)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


D:\anaconda\lib\site-packages\torch\nn\modules\loss.py:431: UserWarning: Using a target size (torch.Size([422])) that is different to the input size (torch.Size([422, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)
tensor(5948.5723, grad_fn=<MseLossBackward>)


In [86]:
# out = net(Variable(torch.from_numpy(x_train)).float())
# print(out[:10])
# print(y_train[:10])

tensor([[153.4803],
        [153.2645],
        [153.4507],
        [153.2097],
        [153.2892],
        [153.3107],
        [153.2753],
        [153.3509],
        [153.4042],
        [153.3828]], grad_fn=<SliceBackward>)
[ 151.   75.  141.  206.  135.   97.  138.   63.  110.  310.]
